#!/bin/bash
#
# Script to manage and build many projects.
#
# Copyright (c) 2014-2015 David I. Lehn
# Author: David I. Lehn <dil@lehn.org>

ROOT=`cd $(dirname $0) && pwd`
. $ROOT/mpm-group-a.conf
GITHUB_BASE=$G_A_GITHUB_BASE
EXTRA_MODS=$G_A_EXTRA_MODS
CLONE_MODS=$G_A_CLONE_MODS
DEFAULT_MODS=$G_A_DEFAULT_MODS
NO_BUILD_MODS=$G_A_NO_BUILD_MODS
MODS=$G_A_MODS

. $ROOT/../mpm/bin/mpm
