#!/bin/bash
#
# mpm group config.
#
# Copyright (c) 2014-2015 David I. Lehn
# Author: David I. Lehn <dil@lehn.org>

G_A_GITHUB_BASE="git@github.com:group-a"
G_A_EXTRA_MODS=""
G_A_CLONE_MODS=" \
project-a \
project-b \
project-c \
"
X_G_A_DEFAULT_MODS=" \
disabled-project-d \
disabled-project-e \
$G_A_CLONE_MODS \
"
G_A_DEFAULT_MODS=" \
$G_A_CLONE_MODS \
"
G_A_NO_BUILD_MODS=" \
"
G_A_MODS=$G_A_DEFAULT_MODS
